### ISSUE TITLE
make_rgb_cube doesn't deal with different hdu extensions

### ISSUE THREAD

**Issue by ksokal** [aplpy/aplpy#207]
Hello, I am using Python 2.6.6 on a Linux.

I am trying to make an rgb image using archive HST files, and I think the problem is that the image is not the primary extension, as aplpy.make_rgb_image assumes.

I have tried three methods of doing this so far.
Method 1:

```
import aplpy
import os
import numpy
import pylab as plt
import montage

fig=plt.figure()
r_file='im1.fits'
g_file='im2.fits'
b_file='im3.fits'
files=[r_file,g_file,b_file]
aplpy.make_rgb_cube(files, output='test'+'_cube.fits',north=True)
```

And then I get this warning:

> WARNING: ConfigurationDefaultMissingWarning: Requested default configuration file /usr/lib/python2.6/site-packages/montage_wrapper/montage_wrapper.cfg is not a file. Cannot install default profile. If you are importing from source, this is expected. [pyfits.core]
> ERROR: MontageError: mProject: NAXIS keyword in FITS header must be >= 2 [montage_wrapper.status]
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.6/site-packages/aplpy/rgb.py", line 301, in make_rgb_cube
>     header=header_hdr, exact_size=True, bitpix=-32)
>   File "/usr/lib/python2.6/site-packages/montage_wrapper/wrappers.py", line 339, in reproject
>     header_hdr, hdu=hdu)
>   File "/usr/lib/python2.6/site-packages/montage_wrapper/wrappers.py", line 204, in mProject_auto
>     m.mProject(_args, *_kwargs)
>   File "/usr/lib/python2.6/site-packages/montage_wrapper/commands.py", line 1642, in mProject
>     return status.parse_struct("mProject", p.stdout.read().strip())
>   File "/usr/lib/python2.6/site-packages/montage_wrapper/status.py", line 33, in parse_struct
>     result = Struct(command, string)
>   File "/usr/lib/python2.6/site-packages/montage_wrapper/status.py", line 70, in **init**
>     raise MontageError("%s: %s" % (command, self.msg))
> montage_wrapper.status.MontageError: mProject: NAXIS keyword in FITS header must be >= 2

so naturally I tried to get around this, as NAXIS=0 in the extension[0] but not [1]...
Method 2: 

```
import aplpy
import os
import numpy
import pylab as plt
import montage

fig=plt.figure()
r_file='im1.fits'
g_file='im2.fits'
b_file='im3.fits'

f1=aplpy.FITSFigure(files[0], hdu=1, figure=fig)
```

> WARNING: DeprecationWarning: The naxis1 attribute is deprecated and may be removed in a future version. [pyfits.core]
> WARNING: DeprecationWarning: The naxis2 attribute is deprecated and may be removed in a future version. [pyfits.core]
> WARNING: Cannot determine equinox. Assuming J2000. [aplpy.wcs_util]
> WARNING: Cannot determine equinox. Assuming J2000. [aplpy.wcs_util]
> WARNING: DeprecationWarning: The wcs_pix2sky function is deprecated and may be removed in a future version.
>        Use wcs_pix2world instead. [pyfits.core]

```
f2=aplpy.FITSFigure(files[1], hdu=1, figure=fig)
```

> WARNING: Cannot determine equinox. Assuming J2000. [aplpy.wcs_util]
> WARNING: Cannot determine equinox. Assuming J2000. [aplpy.wcs_util]
> f3=aplpy.FITSFigure(files[2], hdu=1, figure=fig)>>> f3=aplpy.FITSFigure(files[2], hdu=1, figure=fig)
> WARNING: Cannot determine equinox. Assuming J2000. [aplpy.wcs_util]
> WARNING: Cannot determine equinox. Assuming J2000. [aplpy.wcs_util]

```
aplpy.make_rgb_cube([f1,f2,f3], output='test2'+'_cube.fits',north=True)
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.6/site-packages/aplpy/rgb.py", line 261, in make_rgb_cube
>     if not os.path.exists(f):
>   File "/usr/lib64/python2.6/genericpath.py", line 18, in exists
>     st = os.stat(path)
> TypeError: coercing to Unicode: need string or buffer, FITSFigure found

and lastly,
Method 3:
inspired from http://stackoverflow.com/questions/25327586/montageerror-invalid-table-file
although I don't think he got it working either

```
import aplpy
import os
import numpy
import pylab as plt
import montage
import pyfits

fig=plt.figure()
r_file='im1.fits'
g_file='im2.fits'
b_file='im3.fits'
r=pyfits.open(r_file)
g=pyfits.open(g_file)
b=pyfits.open(b_file)
r.info()
```

> Filename: /net/home/stuff/im1.fits
> No.    Name         Type      Cards   Dimensions   Format
> 0    PRIMARY     PrimaryHDU     759  ()            uint8
> 1    SCI         ImageHDU       107  (4228, 4357)  float32
> 2    WHT         ImageHDU        71  (4228, 4357)  float32
> 3    CTX         ImageHDU        71  (4228, 4357)  int32
> 4    HDRTAB      BinTableHDU    591  6R x 291C     [9A, 3A, J, D, D, D, D, D, D, D, D, D, D, D, D, D, J, 8A, 9A, 7A, 18A, 4A, D, D, D, D, 23A, D, D, D, D, D, D, D, D, D, D, D, D, J, 8A, 23A, D, D, D, D, J, J, J, 8A, J, 23A, 9A, 19A, J, 4A, J, J, J, J, J, J, 23A, D, D, D, D, J, J, 3A, 23A, 4A, 4A, J, D, D, D, 23A, 1A, J, D, D, D, D, D, 4A, 4A, 12A, 12A, 23A, 8A, 23A, 10A, 10A, D, D, 3A, 3A, 23A, 4A, 8A, 7A, 23A, D, J, D, 6A, 9A, 8A, D, D, J, 4A, 18A, 3A, J, 7A, 5A, 3A, D, 13A, 8A, 4A, 3A, J, J, J, J, J, J, J, D, D, D, D, D, D, 23A, 1A, D, 23A, D, D, D, 3A, 23A, J, 1A, 3A, 1A, D, 3A, 6A, J, D, D, D, D, D, D, D, D, D, D, 23A, D, D, D, D, D, D, D, D, 1A, J, J, J, J, J, J, 23A, J, 5A, 7A, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, 12A, D, 24A, 23A, D, 2A, 8A, D, J, D, D, 6A, 4A, D, 19A, J, D, J, 4A, D, D, D, D, D, 23A, 23A, D, 8A, D, 29A, D, 3A, D, J, D, D, 3A, 7A, 8A, 1A, D, 8A, J, 1A, 1A, 1A, 1A, D, D, D, D, D, D, 4A, D, 4A, D, 4A, J, 4A, 23A, 1A, J, J, J, 1A, D, D, D, D, J, 3A, J, J, 6A, J, D, D, 11A, D, D, 3A, 8A, 1A, D, >J, D, J, J, 5A]

```
r1 = r[1].data
g1 = g[1].data
b1 = b[1].data
hdu = pyfits.PrimaryHDU(r1)
hdulist = pyfits.HDUList([hdu])
hdulist.writeto('r.fits')
hdu = pyfits.PrimaryHDU(g1)
hdulist = pyfits.HDUList([hdu])
hdulist.writeto('g.fits')
hdu = pyfits.PrimaryHDU(b1)
hdulist = pyfits.HDUList([hdu])
hdulist.writeto('b.fits')
aplpy.make_rgb_cube(['r.fits','g.fits','b.fits'], 'test_rgb.fits')
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.6/site-packages/aplpy/rgb.py", line 283, in make_rgb_cube
>     montage.mMakeHdr(images_raw_tbl, header_hdr, north_aligned=north, system=system, equinox=equinox)
>   File "/usr/lib/python2.6/site-packages/montage_wrapper/commands.py", line 1468, in mMakeHdr
>     return status.parse_struct("mMakeHdr", p.stdout.read().strip())
>   File "/usr/lib/python2.6/site-packages/montage_wrapper/status.py", line 33, in parse_struct
>     result = Struct(command, string)
>   File "/usr/lib/python2.6/site-packages/montage_wrapper/status.py", line 70, in **init**
>     raise MontageError("%s: %s" % (command, self.msg))
> montage_wrapper.status.MontageError: mMakeHdr: Invalid table file: >/tmp/tmpe_zmc0/images_raw.tbl

I am not sure whether this is actually an issue with aplpy, but it certainly would be nice to be able to specify which hdu to use (as with aplpy.FITSFile).

Thanks for your time!

**Comment by indiajoe** [comment]
I too am facing the same error while using Herschel SPIRE data which also has multiple hdu.

**Comment by Mythemind** [comment]
Still having the same issues mentioned above with HST images, any solutions yet?

**Comment by madoee** [comment]
I too stumbled over this when looking into HST data. The Montage tool does not offer the selection of the HDU (though I only looked into this for a minute), so it's not trivial to add this option to the make_rgb_cube method.

A quick work-around I wrote just takes the FITS files you want to use and saves the image HDU extension as it's own proper FITS file. You can then pass these new files to the method and it works like a charm. Note that you have to specify the image extension yourself.

Here's my code:

```python
import matplotlib
matplotlib.use('Agg')

import aplpy
from astropy.io import fits


def isolate_image_extension(fits_file, extension):
    '''
        Saves the data + header of the specified extension as
        new FITS file

        input
        ------
        fits_file: file path to FITS image
        extension: Number of HDU extension containing the image data
    '''

    header = fits.getheader(fits_file, extension)
    data = fits.getdata(fits_file, extension)

    fits.writeto('%s_image.fits' % fits_file.rstrip('.fits'), data, header)


# Create new FITS files containing only the image extension
for exposure in ['id1k8c010_drz.fits', 'id1k8i010_drz.fits', 'id1k8n010_drz.fits']:
    isolate_image_extension(exposure, 1)

# Call mage_rgb_cube on the isolated image extension
aplpy.make_rgb_cube(['id1k8c010_drz_image.fits', 'id1k8i010_drz_image.fits',
                     'id1k8n010_drz_image.fits'], 'id_rgb.fits')
```
