### ISSUE TITLE
AttributeError: 'WCS' object has no attribute 'naxis1'

### ISSUE THREAD

**Issue by neuronphysics** [aplpy/aplpy#222]
I use aplpy library to make RGB image from astronomical fits file. I used the following lines to set the upper and lower limits of final image. 

import aplpy
import atpy
from pyavm import AVM

aplpy.make_rgb_image('gal_rgb.fits','gal_rgb_arcsinh_contour.png',
                     vmin_r=-0.005, vmax_r=0.2,
                     vmin_g=-0.02, vmax_g=0.1,
                     vmin_b=-0.02,vmax_b=0.04,
                     embed_avm_tags=True)
But when I run the code, I get  the following error message and I couldn't figure out why I got this error? 
File "Plot.Clusters.Contour.Red.Galaxies.py", line 41, in <module>
    embed_avm_tags=True)
  File "/vo/anaconda/lib/python2.7/site-packages/APLpy-0.9.11-py2.7.egg/aplpy/rgb.py", line 201, in make_rgb_image
    avm = AVM.from_header(header)
  File "/vol/anaconda/lib/python2.7/site-packages/pyavm/avm.py", line 520, in from_header
    self = cls.from_wcs(wcs)
  File "/vol/anaconda/lib/python2.7/site-packages/pyavm/avm.py", line 551, in from_wcs
    self.Spatial.ReferenceDimension = [wcs.naxis1, wcs.naxis2]
AttributeError: 'WCS' object has no attribute 'naxis1'

Can anybody explain what is wrong here?

**Comment by neuronphysics** [comment]
Hi again,

I have updated my astropy and I am getting the same error when I run my old scripts.
>>> import astropy
>>> astropy.__file__
'/vol/anaconda/lib/python2.7/site-packages/astropy/__init__.pyc'
>>> astropy.__version__
u'1.0.5'
>>> import aplpy
>>> import atpy
>>> from pyavm import AVM
>>> aplpy.make_rgb_cube(['image_R.fits','image_V.fits','image_U38.fits'],'image_cube.fits')
>>> aplpy.make_rgb_image('image_cube.fits','image_cube.png',  vmin_r=-0.005, vmax_r=0.2,  vmin_g=-0.02, vmax_g=0.1,   vmin_b=-0.02,vmax_b=0.04, embed_avm_tags=False)                                                                                                            
INFO: Red: [aplpy.rgb]
INFO: vmin = -5.000e-03 [aplpy.rgb]
INFO: vmax =  2.000e-01 [aplpy.rgb]
INFO: Green: [aplpy.rgb]
INFO: vmin = -2.000e-02 [aplpy.rgb]
INFO: vmax =  1.000e-01 [aplpy.rgb]
INFO: Blue: [aplpy.rgb]
INFO: vmin = -2.000e-02 [aplpy.rgb]
INFO: vmax =  4.000e-02 [aplpy.rgb]
>>> img = aplpy.FITSFigure('image_cube.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in __init__
  File "/vol/anaconda/lib/python2.7/site-packages/APLpy-0.9.13-py2.7.egg/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/vol/anaconda/lib/python2.7/site-packages/APLpy-0.9.13-py2.7.egg/aplpy/core.py", line 216, in __init__
    data = AVM.from_image(data).to_wcs()
  File "/vol/anaconda/lib/python2.7/site-packages/pyavm/avm.py", line 373, in from_image
    xmp = extract_xmp(filename)
  File "/vol/anaconda/lib/python2.7/site-packages/pyavm/extract.py", line 38, in extract_xmp
    raise NoXMPPacketFound("No XMP packet present in file")
pyavm.exceptions.NoXMPPacketFound: No XMP packet present in file

and if I make RGB image with the following command again I get error message:
>>> aplpy.make_rgb_image('image_cube.fits','image_cube.png')                     
INFO: Red: [aplpy.rgb]
INFO: vmin = -2.404e-02 (auto) [aplpy.rgb]
INFO: vmax =  8.688e-01 (auto) [aplpy.rgb]
INFO: Green: [aplpy.rgb]
INFO: vmin = -4.468e-02 (auto) [aplpy.rgb]
INFO: vmax =  3.759e-01 (auto) [aplpy.rgb]
INFO: Blue: [aplpy.rgb]
INFO: vmin = -6.010e-03 (auto) [aplpy.rgb]
INFO: vmax =  2.402e-02 (auto) [aplpy.rgb]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vol/anaconda/lib/python2.7/site-packages/APLpy-0.9.13-py2.7.egg/aplpy/rgb.py", line 228, in make_rgb_image
    avm = AVM.from_header(header)
  File "/vol/anaconda/lib/python2.7/site-packages/pyavm/avm.py", line 520, in from_header
    self = cls.from_wcs(wcs)
  File "/vol/anaconda/lib/python2.7/site-packages/pyavm/avm.py", line 551, in from_wcs
    self.Spatial.ReferenceDimension = [wcs.naxis1, wcs.naxis2]
AttributeError: 'WCS' object has no attribute 'naxis1'

Any suggestion again to fix the problem?

**Comment by ayyastro** [comment]
I met the same problem WCS' object has no attribute 'naxis1'  when I plot rgb image using apply. I update PyAVM, but the problem still exist. Is anyone fixed this problem? 
Thanks

**Comment by keflavich** [comment]
@ayyastro see https://github.com/aplpy/aplpy/pull/284
