### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode' when current work directory contains .git folder and using python3

### ISSUE THREAD

**Issue by gijzelaerr** [aplpy/aplpy#248]
Hi! i'm using a aplpy in a django project using python3, which works fine, but as soon as I try to run this inside a docker container with WSGI I run into troubles. I get the idea something goes wrong with the stdin handling in that case, but I'm not sure. I've been trying to replicate the problem in a more simple case, but have not been successful yet. Will update this issue if I know more.
```
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/urlresolvers.py", line 364, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'
django_1 |
During handling of the above exception, another exception occurred:
django_1 |
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.4/dist-packages/django/core/urlresolvers.py", line 343, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "./rodrigues/urls.py", line 16, in <module>
    viewer_url = url(r'^viewer/', include('viewer.urls'))
  File "/usr/local/lib/python3.4/dist-packages/django/conf/urls/__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "./viewer/urls.py", line 4, in <module>
    from .views import FitsView,  ListDirView, SomethingView
  File "./viewer/views.py", line 16, in <module>
    import aplpy
  File "/usr/local/lib/python3.4/dist-packages/aplpy/__init__.py", line 9, in <module>
    from ._astropy_init import *
  File "/usr/local/lib/python3.4/dist-packages/aplpy/_astropy_init.py", line 17, in <module>
    from .version import version as __version__
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 151, in <module>
    version = update_git_devstr(_last_generated_version)
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 34, in update_git_devstr
    devstr = get_git_devstr(sha=True, show_warning=False, path=path)
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 144, in get_git_devstr
    return _decode_stdio(stdout)[:40]
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 17, in _decode_stdio
    text = stream.decode(stdio_encoding)
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by astrofrog** [comment]
@gijzelaerr - this is an issue that I thought should be fixed in APLpy 1.0. Which version are you using?

**Comment by gijzelaerr** [comment]
Just checked, that is `APLpy==1.0` for sure.

**Comment by astrofrog** [comment]
@gijzelaerr - I think what might be happening here is that the locale is not correctly set - see:

http://docs.astropy.org/en/v1.0/known_issues.html#locale-errors-in-macos-x-and-linux

Does setting the locale variables correctly help?

**Comment by gijzelaerr** [comment]
That doesn't seem to affect the problem. Also I try to replicate the problem in an isolated environment (new container), but I can't! This is getting weird by the second.

new container:
```
  docker run -ti gijzelaerr/aplpybug bash
root@2219cdd3f730:/code# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
root@2219cdd3f730:/code# python3 -c "import aplpy"
root@2219cdd3f730:/code#
```


failing container:

```
 docker exec -ti c3e36012a2ad bash
root@c3e36012a2ad:/code# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
root@c3e36012a2ad:/code# python3 "import astropy"
python3: can't open file 'import astropy': [Errno 2] No such file or directory
root@c3e36012a2ad:/code# python3 -c "import astropy"
root@c3e36012a2ad:/code# python3 -c "import aplpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/aplpy/__init__.py", line 9, in <module>
    from ._astropy_init import *
  File "/usr/local/lib/python3.4/dist-packages/aplpy/_astropy_init.py", line 17, in <module>
    from .version import version as __version__
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 151, in <module>
    version = update_git_devstr(_last_generated_version)
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 34, in update_git_devstr
    devstr = get_git_devstr(sha=True, show_warning=False, path=path)
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 144, in get_git_devstr
    return _decode_stdio(stdout)[:40]
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 17, in _decode_stdio
    text = stream.decode(stdio_encoding)
AttributeError: 'str' object has no attribute 'decode'
root@c3e36012a2ad:/code# export LANG="en_US.UTF-8"
root@c3e36012a2ad:/code# export LC_ALL="en_US.UTF-8"
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
root@c3e36012a2ad:/code# export LC_CTYPE="en_US.UTF-8"
root@c3e36012a2ad:/code# python3 -c "import aplpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/aplpy/__init__.py", line 9, in <module>
    from ._astropy_init import *
  File "/usr/local/lib/python3.4/dist-packages/aplpy/_astropy_init.py", line 17, in <module>
    from .version import version as __version__
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 151, in <module>
    version = update_git_devstr(_last_generated_version)
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 34, in update_git_devstr
    devstr = get_git_devstr(sha=True, show_warning=False, path=path)
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 144, in get_git_devstr
    return _decode_stdio(stdout)[:40]
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 17, in _decode_stdio
    text = stream.decode(stdio_encoding)
AttributeError: 'str' object has no attribute 'decode'
root@c3e36012a2ad:/code# locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by astrofrog** [comment]
@gijzelaerr - hmm, were both installed from a clean clone of APLpy? I wonder if one may have had residual files (a residual ``version.py`` file). Can you compare the ``/usr/local/lib/python3.4/dist-packages/aplpy/version.py`` files between the two containers?

**Comment by gijzelaerr** [comment]
I can verify that both files are the same, both have md5sum `2306316d739266fde913b4c2ab22e679`

**Comment by astrofrog** [comment]
@gijzelaerr - so just to check, if you create yet another container, does it work? Are you pip-installing APLpy?

**Comment by gijzelaerr** [comment]
Yes I'm pip installing APLpy. I'm trying to isolate the problem a bit more. It is very weird, but when I start the container manually there is no problem, but when I start the same container using fig I run into troubles. All environment variables are the same. Also this only happens when certain python and/or debian packages are installed. It is a very weird edge case.

**Comment by astrofrog** [comment]
I think this problem might go away once I update astropy-helpers, since I think @embray made some changes relating to get_git_devstr.

Just to check, do you have git installed on both machines? (you shouldn't need them on either, but just checking if that could make a difference)

**Comment by gijzelaerr** [comment]
Ok I found the problem. It has nothing to do with Docker & fig.

$ python3 -c "import aplpy"
$ mkdir .git
$ python3 -c "import aplpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/aplpy/__init__.py", line 9, in <module>
    from ._astropy_init import *
  File "/usr/local/lib/python3.4/dist-packages/aplpy/_astropy_init.py", line 17, in <module>
    from .version import version as __version__
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 151, in <module>
    version = update_git_devstr(_last_generated_version)
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 34, in update_git_devstr
    devstr = get_git_devstr(sha=True, show_warning=False, path=path)
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 144, in get_git_devstr
    return _decode_stdio(stdout)[:40]
  File "/usr/local/lib/python3.4/dist-packages/aplpy/version.py", line 17, in _decode_stdio
    text = stream.decode(stdio_encoding)
AttributeError: 'str' object has no attribute 'decode'

**Comment by astrofrog** [comment]
Ah, good catch. I think this will be fixed by updating astropy-helpers since I think that now git won't get called for stable releases.

**Comment by gijzelaerr** [comment]
The `astropy-helpers` was not installed. When I install `astropy-helpers-1.0.1` i keep the same problem.

**Comment by astrofrog** [comment]
@gijzelaerr - astropy-helpers is not meant to be installed, but rather I need to update the submodule version and the bundled astropy-helpers. I'll do that later today.

**Comment by gijzelaerr** [comment]
awesome, thanks Thomas.

**Comment by embray** [comment]
Yeah, that's just a (known, but fixed) bug in the `aplpy.version` module, which is a source file that gets *generated* by astropy-helpers.  It is admittedly crazy confusing when you have a bug in code that gets generated for your project by another project.
