### ISSUE TITLE
Tick label d.d format doesn't work

### ISSUE THREAD

**Issue by cdeil** [aplpy/aplpy#250]
I'd like to use a `d.d` format for the tick labels.
This works in `wcsaxes`, but in `aplpy` I get this error:

``` python
>>> from wcsaxes import datasets
>>> from aplpy import FITSFigure
>>> hdu = datasets.fetch_msx_hdu()
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
>>> ff = FITSFigure(hdu)
>>> ff.show_colorscale()
INFO: Auto-setting vmin to -2.612e-05 [aplpy.core]
INFO: Auto-setting vmax to  2.966e-04 [aplpy.core]
>>> ff.tick_labels.set_yformat('d.d')
>>> ff.save('fig.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/APLpy-2.0.dev832-py3.4.egg/aplpy/core.py", line 1775, in save
    self._figure.savefig(filename, dpi=dpi, transparent=transparent, bbox_inches='tight', bbox_extra_artists=artists, format=format)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/figure.py", line 1476, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/backend_bases.py", line 2158, in print_figure
    **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/backends/backend_agg.py", line 521, in print_png
    FigureCanvasAgg.draw(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/backends/backend_agg.py", line 469, in draw
    self.figure.draw(self.renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/figure.py", line 1085, in draw
    func(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mpl_toolkits/axes_grid1/parasite_axes.py", line 295, in draw
    self._get_base_axes_attr("draw")(self, renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mpl_toolkits/axisartist/axislines.py", line 772, in draw
    super(Axes, self).draw(renderer, inframe)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axes/_base.py", line 2110, in draw
    a.draw(renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/artist.py", line 59, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axis.py", line 1114, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axis.py", line 957, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axis.py", line 957, in <listcomp>
    tick_tups = [t for t in self.iter_ticks()]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axis.py", line 905, in iter_ticks
    for i, val in enumerate(majorLocs)]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/matplotlib/axis.py", line 905, in <listcomp>
    for i, val in enumerate(majorLocs)]
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/APLpy-2.0.dev832-py3.4.egg/aplpy/labels.py", line 424, in __call__
    label = label.tostringlist(format=self.axis.apl_label_form, sep=sep)
  File "/Users/deil/Library/Python/3.4/lib/python/site-packages/APLpy-2.0.dev832-py3.4.egg/aplpy/angle_util.py", line 209, in tostringlist
    string[0] = "-" + string[0]
IndexError: list index out of range
```

cc @adonath

**Comment by astrofrog** [comment]
I think this should now work properly with APLpy 2.0!
