### ISSUE TITLE
Contour Error

### ISSUE THREAD

**Issue by astroHam** [aplpy/aplpy#251]
Hi,

Keep getting an error with specifying contours.
Using the line img.show_contour(cohdu,levels=[3.,5.,7.,9.],colors=['black','w','w','w'])
you get the following error message.

WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
INFO: Setting slices=[0] [aplpy.core]
WARNING: FITSFixedWarning: 'spcfix' made the change 'Changed CTYPE3 from 'FELO-LSR' to 'VOPT-F2W''. [astropy.wcs.wcs]
INFO: Setting slices=[0] [aplpy.core]
Traceback (most recent call last):
  File "fig_Lupus.py", line 21, in <module>
    img.show_contour(cohdu,levels=[3.,5.,7.,9.],colors=['black','w','w','w'])
  File "<string>", line 2, in show_contour
  File "/Users/macham/anaconda/lib/python2.7/site-packages/APLpy-1.0-py2.7.egg/aplpy/decorators.py", line 25, in _auto_refresh
    return f(_args, *_kwargs)
  File "/Users/macham/anaconda/lib/python2.7/site-packages/APLpy-1.0-py2.7.egg/aplpy/core.py", line 925, in show_contour
    slices=slices)
  File "/Users/macham/anaconda/lib/python2.7/site-packages/APLpy-1.0-py2.7.egg/aplpy/core.py", line 426, in _get_hdu
    wcs = wcs_util.WCS(header, dimensions=dimensions, slices=slices, relax=True)
  File "/Users/macham/anaconda/lib/python2.7/site-packages/APLpy-1.0-py2.7.egg/aplpy/wcs_util.py", line 33, in __init__
    AstropyWCS.**init**(self, _args, *_kwargs)
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/wcs/wcs.py", line 381, in **init**
    new_header[dict_key] = header[dict_key]
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/io/fits/header.py", line 195, in **setitem**
    self._update((key, value, comment))
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1666, in _update
    cards = self._splitcommentary(keyword, value)
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1908, in _splitcommentary
    cards.append(Card(keyword, valuestr[idx:idx + maxlen]))
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/io/fits/card.py", line 448, in __init__
    self.value = value
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/io/fits/card.py", line 603, in value
    'represent printable characters in ASCII.' % value)
ValueError: FITS header values must contain standard printable ASCII characters; "CREATOR = 'COMB 2000.2'        /\nCOMB TITLE lui Data Cube\nCOMB PARAM ir:" contains characters/bytes that do not represent printable characters in ASCII.

I have the latest version of Aplpy and astropy.
Anyone have similar problems? Solutions?

**Comment by astrofrog** [comment]
@astroHam - could you try running:

```
fitscheck your_fits_file.fits
```

on the command-line? (``fitscheck`` comes with Astropy) Let me know the output here. Thanks!

It looks like the ``CREATOR`` keyword contains newline characters which is not allowed. You could always do:

```
cohdu.header["CREATOR"] = ""
```

before calling APLpy.

**Comment by astroHam** [comment]
Hi Thomas,

Tried the fitscheck got one error 'Checksum not found in HDU #0'.

The CREATOR tag is part is actually within the history section.
I cleared the history, I still get the following error:

Traceback (most recent call last):
  File "fig_Lupus.py", line 21, in <module>
    img.show_contour(cohdu,levels=[3.,5.,7.,9.],colors=['black','w','w','w'])
  File "<string>", line 2, in show_contour
  File "/Users/macham/anaconda/lib/python2.7/site-packages/APLpy-1.0-py2.7.egg/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/Users/macham/anaconda/lib/python2.7/site-packages/APLpy-1.0-py2.7.egg/aplpy/core.py", line 925, in show_contour
    slices=slices)
  File "/Users/macham/anaconda/lib/python2.7/site-packages/APLpy-1.0-py2.7.egg/aplpy/core.py", line 426, in _get_hdu
    wcs = wcs_util.WCS(header, dimensions=dimensions, slices=slices, relax=True)
  File "/Users/macham/anaconda/lib/python2.7/site-packages/APLpy-1.0-py2.7.egg/aplpy/wcs_util.py", line 33, in __init__
    AstropyWCS.__init__(self, *args, **kwargs)
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/wcs/wcs.py", line 381, in __init__
    new_header[dict_key] = header[dict_key]
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/io/fits/header.py", line 195, in __setitem__
    self._update((key, value, comment))
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1666, in _update
    cards = self._splitcommentary(keyword, value)
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1901, in _splitcommentary
    cards = [Card(keyword, value)]
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/io/fits/card.py", line 448, in __init__
    self.value = value
  File "/Users/macham/anaconda/lib/python2.7/site-packages/astropy/io/fits/card.py", line 570, in value
    raise ValueError('Illegal value: %r.' % value)
ValueError: Illegal value:


________________________________

**Comment by astrofrog** [comment]
It looks like this was due to an invalid FITS file (specifically non-ASCII characters in the header) so I'll go ahead and close this.
