### ISSUE TITLE
attempt to read ds9 region files fails with "ValueError: too many values to unpack"

### ISSUE THREAD

**Issue by aakepley** [aplpy/aplpy#295]
I'm trying to overlay ds9 regions on an image. The aplpy script worked fine just a couple months ago, but is failing horribly now when I try and overplot the ds9 regions. I've put the details below.
[pyregion_test.zip](https://github.com/aplpy/aplpy/files/271191/pyregion_test.zip)

```
import aplpy
import matplotlib.pyplot as mpl

mom8Image = 'co32_r0_2kms_uvmatched_K.mom8.fits'

fig = mpl.figure(figsize=(10,6),edgecolor='white',facecolor='white')
fig.subplots_adjust(left=0.0,bottom=0.0,right=1.0,top=1.0)

f0 = aplpy.FITSFigure(mom8Image,figure=fig)
f0.show_regions('cloudA.reg')
```

```
WARNING: AstropyDeprecationWarning: The ascard function is deprecated and may be removed in a future version.                 
        Use the `.cards` attribute instead. [astropy.utils.decorators]                                                        
---------------------------------------------------------------------------                                                   
ValueError                                Traceback (most recent call last)                                                   
<ipython-input-1-843dc4af649a> in <module>()                                                                                  
----> 1 execfile('pyregion_test_code.py')                                                                                     

/lustre/cv/akepley/IIZw40_alma/r31/pyregion_test_code.py in <module>()
      8                                                               
      9 f0 = aplpy.FITSFigure(mom8Image,figure=fig)                   
---> 10 f0.show_regions('cloudA.reg')                                 
     11                                                               

/users/akepley/anaconda2/lib/python2.7/site-packages/aplpy/regions.pyc in show_regions(self, region_file, layer, **kwargs)

/users/akepley/anaconda2/lib/python2.7/site-packages/aplpy/decorators.pyc in _auto_refresh(f, *args, **kwargs)
     23     mydata.nesting = getattr(mydata, 'nesting', 0) + 1                                                
     24     try:                                                                                              
---> 25         return f(*args, **kwargs)                                                                     
     26     finally:                                                                                          
     27         mydata.nesting -= 1                                                                           

/users/akepley/anaconda2/lib/python2.7/site-packages/aplpy/regions.pyc in show_regions(self, region_file, layer, **kwargs)
     62         """                                                                                                       
     63                                                                                                                   
---> 64         PC, TC = ds9(region_file, self._header, **kwargs)                                                         
     65                                                                                                                   
     66         # ffpc = self._ax1.add_collection(PC)                                                                     

/users/akepley/anaconda2/lib/python2.7/site-packages/aplpy/regions.pyc in ds9(region_file, header, zorder, **kwargs)
    100
    101     # convert coordinates to image coordinates
--> 102     rrim = rr.as_imagecoord(header)
    103
    104     # pyregion and aplpy both correct for the FITS standard origin=1,1

/users/akepley/anaconda2/lib/python2.7/site-packages/pyregion/__init__.pyc in as_imagecoord(self, header, rot_wrt_axis)
     55         r = RegionParser.sky_to_image(zip(self, comment_list),
     56                                       header, rot_wrt_axis=rot_wrt_axis)
---> 57         shape_list, comment_list = zip(*list(r))
     58         return ShapeList(shape_list, comment_list=comment_list)
     59

/users/akepley/anaconda2/lib/python2.7/site-packages/pyregion/ds9_region_parser.pyc in sky_to_image(l, header, rot_wrt_axis)
    182             if isinstance(l1, Shape) and \
    183                    (l1.coord_format not in image_like_coordformats):
--> 184                 tgt = wcs_proj.radesys
    185                 if l1.coord_format == UnknownWcs:
    186                     src = tgt

/users/akepley/anaconda2/lib/python2.7/site-packages/pyregion/wcs_helper.pyc in _get_radesys(self)
    228
    229     def _get_radesys(self):
--> 230         ctype1, ctype2 = self.ctypes
    231         equinox = self.equinox
    232         radecsys = coord_system_guess(ctype1, ctype2, equinox)

ValueError: too many values to unpack

```

I'm running pyregion 1.1.4, pyparsing 2.0.3, and aplpy 1.0. Let me know if you need any more info.

Amanda

**Comment by revoltek** [comment]
Same problem here:
```
Traceback (most recent call last):
  File "./plot_image.py", line 39, in <module>
    gc.show_regions('vlss.reg')
  File "<string>", line 2, in show_regions
  File "/usr/lib/python2.7/dist-packages/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/aplpy/regions.py", line 64, in show_regions
    PC, TC = ds9(region_file, self._header, **kwargs)
  File "/usr/lib/python2.7/dist-packages/aplpy/regions.py", line 102, in ds9
    rrim = rr.as_imagecoord(header)
  File "/usr/lib/python2.7/dist-packages/pyregion/__init__.py", line 57, in as_imagecoord
    shape_list, comment_list = zip(*list(r))
  File "/usr/lib/python2.7/dist-packages/pyregion/ds9_region_parser.py", line 184, in sky_to_image
    tgt = wcs_proj.radesys
  File "/usr/lib/python2.7/dist-packages/pyregion/wcs_helper.py", line 230, in _get_radesys
    ctype1, ctype2 = self.ctypes
ValueError: too many values to unpack
```
I think it's related with the fits file having degenerate axes. The problem might be of pyregion though.
