### ISSUE TITLE
Can not load fits file with FITSFigure

### ISSUE THREAD

**Issue by amisk** [aplpy/aplpy#305]
Hi,

I basically use this: 
gc = aplpy.FITSFigure('PI2.fits')

and it always crashes:
WARNING: FITSFixedWarning: The WCS transformation has more axes (4) than the image it is associated with (2) [astropy.wcs.wcs]
Traceback (most recent call last):
  File "plot_magfield.py", line 11, in <module>
    gc = aplpy.FITSFigure('PI2.fits')
  File "<string>", line 2, in __init__
  File "/usr/local/lib/python2.7/dist-packages/APLpy-1.0-py2.7.egg/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/APLpy-1.0-py2.7.egg/aplpy/core.py", line 326, in __init__
    self.set_theme(theme='pretty')
  File "<string>", line 2, in set_theme
  File "/usr/local/lib/python2.7/dist-packages/APLpy-1.0-py2.7.egg/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/APLpy-1.0-py2.7.egg/aplpy/core.py", line 1812, in set_theme
    self.ticks.set_color('white')
  File "<string>", line 2, in set_color
  File "/usr/local/lib/python2.7/dist-packages/APLpy-1.0-py2.7.egg/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/APLpy-1.0-py2.7.egg/aplpy/ticks.py", line 137, in set_color
    for line in self._ax1.xaxis.get_ticklines():
  File "/usr/lib/pymodules/python2.7/matplotlib/axis.py", line 1185, in get_ticklines
    return self.get_majorticklines()
  File "/usr/lib/pymodules/python2.7/matplotlib/axis.py", line 1166, in get_majorticklines
    ticks = self.get_major_ticks()
  File "/usr/lib/pymodules/python2.7/matplotlib/axis.py", line 1244, in get_major_ticks
    numticks = len(self.get_major_locator()())
  File "/usr/local/lib/python2.7/dist-packages/APLpy-1.0-py2.7.egg/aplpy/ticks.py", line 313, in __call__
    self.axis.apl_tick_spacing = default_spacing(self.axis.get_axes(), self.coord, self.axis.apl_label_form)
  File "/usr/local/lib/python2.7/dist-packages/APLpy-1.0-py2.7.egg/aplpy/ticks.py", line 351, in default_spacing
    px, py, wx, wy = axis_positions(wcs, coord, False, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax)
  File "/usr/local/lib/python2.7/dist-packages/APLpy-1.0-py2.7.egg/aplpy/ticks.py", line 572, in axis_positions
    x_world, y_world = wcs_util.pix2world(wcs, x_pix, y_pix)
  File "/usr/local/lib/python2.7/dist-packages/APLpy-1.0-py2.7.egg/aplpy/wcs_util.py", line 492, in pix2world
    return wcs.wcs_pix2world(x_pix, y_pix, 1)
  File "/usr/local/lib/python2.7/dist-packages/APLpy-1.0-py2.7.egg/aplpy/wcs_util.py", line 192, in wcs_pix2world
    coords.append(np.repeat(self._slices[s] + 0.5, x.shape))
IndexError: list index out of range

I tried two different fits files created by different software, so I am sure that the fits files themselves should be ok.

**Comment by gogrean** [comment]
You hopefully figured it out by now, but just in case... Your files are probably okay, they just have more than two dimensions. You need to set the `slice` argument. The examples here should help: http://aplpy.readthedocs.io/en/latest/slicing.html

**Comment by astrofrog** [comment]
Thanks @gogrean! I'll close this for now, but @amisk feel free to open a new issue if that doesn't solve your problem, and provide a link to the FITS file you are trying to read.
