### ISSUE TITLE
FITSFigure with `figure` argument causes exception

### ISSUE THREAD

**Issue by evertrol** [aplpy/aplpy#344]
The AplPy documentation for `FITSFigure` states I can pass it a `matplotlib.figure.Figure` instance to attach the plot to.
Yet, the following code raises an exception:

```python
import numpy as np
from matplotlib.figure import Figure
from astropy.io import fits
import aplpy

print(aplpy.__version__)
hdu = fits.PrimaryHDU(data=np.ones((100, 100)))
figure = Figure((12, 12))
print(type(figure))
fig = aplpy.FITSFigure(data=hdu, figure=figure)
```

This has the following output:

```python
1.1.1
<class 'matplotlib.figure.Figure'>
WARNING: No WCS information found in header - using pixel coordinates [aplpy.header]
Traceback (most recent call last):
  File "testaplpy2.py", line 10, in <module>
    fig = aplpy.FITSFigure(data=hdu, figure=figure)
  File "<string>", line 2, in __init__
  File "/usr/local/lib/python3.6/site-packages/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/aplpy/core.py", line 273, in __init__
    self.tick_labels = TickLabels(self)
  File "/usr/local/lib/python3.6/site-packages/aplpy/labels.py", line 72, in __init__
    self._figure.canvas.mpl_connect('key_press_event', self._set_cursor_prefs)
AttributeError: 'NoneType' object has no attribute 'mpl_connect'
```

Am I using the `figure` argument incorrectly?

Note: the penultimate line in the traceback appears to connect a `key_press_event`, which suggests a problem with an interactive backend. Yet, adding the following two lines to the above code, before all other imports, results in the same error:
```python
import matplotlib
matplotlib.use('Agg')
```
so it appears attempting to use a non-interactive backend doesn't solve the issue.

**Comment by saimn** [comment]
It works with `plt.figure`, which seems to do more things to create the Figure instance.

**Comment by evertrol** [comment]
Thanks @saimn , that put me on the right track.
The non-interactive/OO version then becomes:
```python
figure = Figure((12, 12))
canvas = FigureCanvas(figure)
fig = aplpy.FITSFigure(data=hdu, figure=figure)
```
(I usually add the canvas at the very end, which is where my confusion comes from.)

It might be worth a short note somewhere in the docstring.  
Or perhaps, we should assume that someone using the non-pyplot interface knows the canvas needs to be added to the figure.

**Comment by astrofrog** [comment]
We could just raise a clearer error message if ``canvas`` is None which says that the user probably forgot to initialize the canvas manually.
