### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by olebole** [aplpy/aplpy#385]
The current release of aplpy (1.1.1) is probably not fully compatible to astropy 3.0, as seen in the [Debian CI test](https://ci.debian.net/data/autopkgtest/unstable/amd64/a/aplpy/139087/log.gz):
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/_pytest/config.py", line 328, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/usr/lib/python3/dist-packages/aplpy')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/_pytest/config.py", line 359, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/usr/lib/python3/dist-packages/aplpy/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/_pytest/config.py", line 365, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/lib/python3/dist-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py", line 213, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/lib/python3/dist-packages/aplpy/conftest.py", line 6, in <module>
    from astropy.tests.pytest_plugins import pytest_addoption as astropy_pytest_addoption
ImportError: cannot import name 'pytest_addoption'
ERROR: could not load /usr/lib/python3/dist-packages/aplpy/conftest.py
```
At least this seems to however be fixed in the `HEAD`.

Would it be possible to create a new release to stay in sync with astropy?

**Comment by astrofrog** [comment]
APLpy 2.0 is out! 🎉
