### ISSUE TITLE
ValueError: arange: cannot compute length

### ISSUE THREAD

**Issue by tash-mc** [aplpy/aplpy#397]
I am trying to load a fits file I a working with but I receive the following error and have no idea how to fix it? The fits file seems to be working in kvis and other packages.

natasha@sci-5744-u:~/MRes$ python VisualisationScript.py 
/home/natasha/anaconda3/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
/home/natasha/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/natasha/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
INFO: Setting slices=[0] [aplpy.core]
WARNING: FITSFixedWarning: 'spcfix' made the change 'Changed CTYPE3 from 'VELO-LSR' to 'VOPT' (VELREF=0)'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "VisualisationScript.py", line 4, in <module>
    GASS_High = aplpy.FITSFigure('GASS_IntegratedIntensity_HighVelocity.fits')
  File "<string>", line 2, in __init__
  File "/home/natasha/.local/lib/python3.6/site-packages/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/home/natasha/.local/lib/python3.6/site-packages/aplpy/core.py", line 289, in __init__
    self.set_theme(theme='pretty')
  File "<string>", line 2, in set_theme
  File "/home/natasha/.local/lib/python3.6/site-packages/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/home/natasha/.local/lib/python3.6/site-packages/aplpy/core.py", line 1769, in set_theme
    self.ticks.set_color('white')
  File "<string>", line 2, in set_color
  File "/home/natasha/.local/lib/python3.6/site-packages/aplpy/decorators.py", line 25, in _auto_refresh
    return f(*args, **kwargs)
  File "/home/natasha/.local/lib/python3.6/site-packages/aplpy/ticks.py", line 137, in set_color
    for line in self._ax1.xaxis.get_ticklines():
  File "/home/natasha/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1315, in get_ticklines
    return self.get_majorticklines()
  File "/home/natasha/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1296, in get_majorticklines
    ticks = self.get_major_ticks()
  File "/home/natasha/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1396, in get_major_ticks
    numticks = len(self.get_major_locator()())
  File "/home/natasha/.local/lib/python3.6/site-packages/aplpy/ticks.py", line 327, in __call__
    px, py, wx = tick_positions(self._wcs, tick_spacing, self.coord, self.coord, farside=self.farside, xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax, mode='xscaled')
  File "/home/natasha/.local/lib/python3.6/site-packages/aplpy/ticks.py", line 484, in tick_positions
    for w in np.arange(np.floor(min(warr)), np.ceil(max(warr)), 1.):
ValueError: arange: cannot compute length

**Comment by astrofrog** [comment]
I think this issue should be fixed now that APLpy 2.0 is out. Please open a new issue with the data and code you are using if you still run into issues with APLpy 2.0.
