### ISSUE TITLE
Errors in "recenter" and "show_contour"

### ISSUE THREAD

**Issue by AstroDocCarl** [aplpy/aplpy#423]
I am attempting to remake figures using fits files from ALMA/CASA that worked in versions 1 and prior. However now, I am getting lots of errors and I just cannot parse what is going on.

First I get this error: 

 `TypeError: WCS projection has 4 dimensions, so expected 2 (an Nx4 array and the origin argument) or 5 arguments (the position in each dimension, and the origin argument). Instead, 3 arguments were given.` 

The traceback points to the use of my use of

`line_map.recenter(x,y,radius=(1.5/3600.))`

If I comment out this line, then the image will be plotted correctly, however then I get another error at the use of  'show_contour' at which point I get 

`ValueError:` The output dimension of 'a' must be equal to the input dimensions of 'b'

Any suggestions would be very helpful.

**Comment by astrofrog** [comment]
@AstroDocCarl - thanks for reporting the issues. Could you provide the full error tracebacks in both cases?

**Comment by mooneyse** [comment]
Hi there, I am getting a similar error. Here's the traceback:

```
Traceback (most recent call last):
  File "./cutouts.py", line 80, in <module>
    main()
  File "./cutouts.py", line 76, in main
    make_cut_out_image(sources)
  File "./cutouts.py", line 50, in make_cut_out_image
    image.recenter(ra, dec, radius=1)
  File "/usr/local/lib/python3.6/dist-packages/astropy/utils/decorators.py", line 842, in recenter
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "/usr/local/lib/python3.6/dist-packages/aplpy/decorators.py", line 28, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/aplpy/core.py", line 491, in recenter
    xpix, ypix = self.world2pixel(x, y)
  File "/usr/local/lib/python3.6/dist-packages/aplpy/core.py", line 1890, in world2pixel
    return wcs.wcs_world2pix(xw, yw, 0)
  File "/usr/local/lib/python3.6/dist-packages/astropy/wcs/wcs.py", line 2176, in wcs_world2pix
    'input', *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/astropy/wcs/wcs.py", line 1293, in _array_converter
    self.naxis, self.naxis + 1, len(args)))
TypeError: WCS projection has 4 dimensions, so expected 2 (an Nx4 array and the origin argument) or 5 arguments (the position in each dimension, and the origin argument). Instead, 3 arguments were given.
```

It runs successfully when I remove the `recenter` line.

Inspecting the data shape with Astropy:
```
hdu = fits.open(fits_file)[0]
print('Shape:', hdu.data.shape)
```

I get `Shape: (1, 1, 19845, 19845)`. If I do `new_data = np.squeeze(hdu.data)`, feed this `new_data` to `FITSFigure` and convert the `recenter` coordinates to pixels, I can get an image. But this doesn't work with `show_regions`.

Thanks.

**Comment by AstroDocCarl** [comment]
Sorry for not getting back with my traceback. But now I am also trying to make an image of some VLA data (Reduce with casa 5.0 I believe) and I have the same issue with the recenter. Here is my traceback now.

`TypeError                                 Traceback (most recent call last)
<ipython-input-15-80288fb5093a> in <module>
      2 
      3 line_map = aplpy.FITSFigure(b16,figure=fig,size='30')
----> 4 line_map.recenter(x,y,radius=(4.5/3600.))
      5 #gist_heat
      6 line_map.show_colorscale(cmap='viridis',stretch='arcsinh',

~/anaconda3/lib/python3.7/site-packages/astropy/utils/decorators.py in recenter(self, x, y, radius, width, height)
    840             name = func.__name__
    841 
--> 842         func = make_function_with_signature(func, name=name, **wrapped_args)
    843         func = functools.update_wrapper(func, wrapped, assigned=assigned,
    844                                         updated=updated)

~/anaconda3/lib/python3.7/site-packages/aplpy/decorators.py in wrapper(*args, **kwargs)
     26 
     27         try:
---> 28             return f(*args, **kwargs)
     29         finally:
     30             mydata.nesting -= 1

~/anaconda3/lib/python3.7/site-packages/aplpy/core.py in recenter(self, x, y, radius, width, height)
    489         """
    490 
--> 491         xpix, ypix = self.world2pixel(x, y)
    492 
    493         pix_scale = proj_plane_pixel_scales(self._wcs)

~/anaconda3/lib/python3.7/site-packages/aplpy/core.py in world2pixel(self, xw, yw, wcs)
   1888         if wcs is None:
   1889             wcs = self._wcs
-> 1890         return wcs.wcs_world2pix(xw, yw, 0)
   1891 
   1892     def pixel2world(self, xp, yp, wcs=None):

~/anaconda3/lib/python3.7/site-packages/astropy/wcs/wcs.py in wcs_world2pix(self, *args, **kwargs)
   2172         return self._array_converter(
   2173             lambda xy, o: self.wcs.s2p(xy, o)['pixcrd'],
-> 2174             'input', *args, **kwargs)
   2175     wcs_world2pix.__doc__ = """
   2176         Transforms world coordinates to pixel coordinates, using only

~/anaconda3/lib/python3.7/site-packages/astropy/wcs/wcs.py in _array_converter(self, func, sky, ra_dec_order, *args)
   1289             "dimension, and the origin argument). Instead, {2} arguments were "
   1290             "given.".format(
-> 1291                 self.naxis, self.naxis + 1, len(args)))
   1292 
   1293     def all_pix2world(self, *args, **kwargs):

TypeError: WCS projection has 4 dimensions, so expected 2 (an Nx4 array and the origin argument) or 5 arguments (the position in each dimension, and the origin argument). Instead, 3 arguments were given.`

**Comment by nickalaskreynolds** [comment]
I have had the same error too, I resolved it by downgrading to <Version: 1.1.1> as anything >=2.0 induces the error. I can provide a separate traceback if needed but above traceback summarizes my own findings as well.

**Comment by bmarcote** [comment]
Same error when using APLpy 2.1.dev01152, Astropy 4.0 (over Python 3.7.7) in both show_contour and recenter functions. For the former one the error is:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/sources/CWBs/REX1/LBA/script-plot-with-dust.py in <module>
    108
    109 fig.show_colorscale(cmap='viridis', stretch='sqrt', interpolation='bicubic', vmax=0.02)
--> 110 fig.show_contour(fitsimage, colors='w', levels=contours_r1, linewidth=0.5, alpha=0.7, interpolation='bicubic', layer='cont')
    111
    112 # fig.show_lines(position_lines, color='k', layer='line_set', alpha=1, linewidth=1.5)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aplpy/decorators.py in wrapper(*args, **kwargs)
     26
     27         try:
---> 28             return f(*args, **kwargs)
     29         finally:
     30             mydata.nesting -= 1

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aplpy/core.py in show_contour(self, data, hdu, layer, levels, filled, cmap, colors, returnlevels, convention, dimensions, slices, smooth, kernel, overlap, **kwargs)
    965         else:
    966             c = self.ax.contour(image_contour, levels,
--> 967                                 transform=self.ax.get_transform(frame),
    968                                 cmap=cmap,
    969                                 colors=colors, **kwargs)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/visualization/wcsaxes/core.py in get_transform(self, frame)
    561                 * :class:`~astropy.coordinates.BaseCoordinateFrame` instance.
    562         """
--> 563         return self._get_transform_no_transdata(frame).inverted() + self.transData
    564
    565     def _get_transform_no_transdata(self, frame):

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/visualization/wcsaxes/core.py in _get_transform_no_transdata(self, frame)
    570         if isinstance(frame, WCS):
    571
--> 572             transform, coord_meta = transform_coord_meta_from_wcs(frame, self.frame_class)
    573             transform_world2pixel = transform.inverted()
    574

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/visualization/wcsaxes/wcsapi.py in transform_coord_meta_from_wcs(wcs, frame_class, slices)
     29     if wcs.pixel_n_dim > 2:
     30         if slices is None:
---> 31             raise ValueError("WCS has more than 2 pixel dimensions, so "
     32                              "'slices' should be set")
     33         elif len(slices) != wcs.pixel_n_dim:

ValueError: WCS has more than 2 pixel dimensions, so 'slices' should be set
```

And for recenter:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/sources/CWBs/REX1/LBA/script-plot-with-dust.py in <module>
    112 # fig.show_lines(position_lines, color='k', layer='line_set', alpha=1, linewidth=1.5)
    113
--> 114 fig.recenter(lba_center.ra.deg, lba_center.dec.deg, radius=0.055/3600.)
    115 fig.show_markers(lba_center.ra.deg, lba_center.dec.deg, layer='LBA', marker='+', color='k', zorder=15, s=200)
    116

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aplpy/decorators.py in wrapper(*args, **kwargs)
     26
     27         try:
---> 28             return f(*args, **kwargs)
     29         finally:
     30             mydata.nesting -= 1

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aplpy/core.py in recenter(self, x, y, radius, width, height)
    489         """
    490
--> 491         xpix, ypix = self.world2pixel(x, y)
    492
    493         pix_scale = proj_plane_pixel_scales(self._wcs)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/aplpy/core.py in world2pixel(self, xw, yw, wcs)
   1888         if wcs is None:
   1889             wcs = self._wcs
-> 1890         return wcs.wcs_world2pix(xw, yw, 0)
   1891
   1892     def pixel2world(self, xp, yp, wcs=None):

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/wcs/wcs.py in wcs_world2pix(self, *args, **kwargs)
   2189         return self._array_converter(
   2190             lambda xy, o: self.wcs.s2p(xy, o)['pixcrd'],
-> 2191             'input', *args, **kwargs)
   2192     wcs_world2pix.__doc__ = """
   2193         Transforms world coordinates to pixel coordinates, using only

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/wcs/wcs.py in _array_converter(self, func, sky, ra_dec_order, *args)
   1306             "dimension, and the origin argument). Instead, {2} arguments were "
   1307             "given.".format(
-> 1308                 self.naxis, self.naxis + 1, len(args)))
   1309
   1310     def all_pix2world(self, *args, **kwargs):

TypeError: WCS projection has 4 dimensions, so expected 2 (an Nx4 array and the origin argument) or 5 arguments (the position in each dimension, and the origin argument). Instead, 3 arguments were given.
```

Both functions work properly in APLpy 1.1.1 and in principle same astropy 4.0 (over Python 3.6).

**Comment by gwong-astro** [comment]
I am also seeing a similar error with show_rectangles.

**Comment by akdiaz** [comment]
Hi,

you are getting this error ¨TypeError: WCS projection has 4 dimensions, so expected 2 (an Nx4 array and the origin argument) or 5 arguments (the position in each dimension, and the origin argument). Instead, 3 arguments were given." because CASA exports the FITS file by default with four axes (ra, dec, stokes and frequency). Use the parameter dropdeg = True in exportfits. This will export a FITS file with only two axes (the coordinates axes).

Best, AK

**Comment by emoravec** [comment]
@akdiaz, thank you very much!

**Comment by bmarcote** [comment]
Hi @akdiaz,
This also happens with other (radio) tools as both programs, AIPS and Difmap, for example, had the same approach and produces the same type of FITS file, with the default four axes. However, this approach was not given any issue in APlpy 1.1.x.
Any reason for why the behavior changed and it is not accepted any more (or why it couldn't be brought again)?

**Comment by akdiaz** [comment]
Hi @bmarcote, I had no idea this was different in previous versions of APlpy. I encountered this error for the first time working with fits in Astropy a while ago (I don't remember when exactly), so maybe the change comes from Astropy instead?

**Comment by bmarcote** [comment]
It is true that it also happen when working with fits directly in Astropy (although then it is solved by specifying the axes to use).
But this issue in particular is related to APLpy, as with the newer versions of Astropy, but keeping APLpy 1.1.1 it seems to work (at least it did for a while, as nowadays due to other changes in the newest version of Astropy, APLpy 1.1.1 is unusable, but not because of this).

In this case, I am actually not sure what has changed concerning this.

In principle, APLpy should be able to recover the information via specifying the correct `dimensions` and `slices`. However I have been unable to make all functions working in this case (mainly `recenter` and `show_contours`). Maybe it is just my fault on not properly setting the correct parameters there!
As you mention before, almost all these FITS files contain four axes: (ra, dec, stokes and frequency; last both can be swapped depending on the previous programs used to generate it). Therefore, via Astropy.io.fits it can be plotted setting `slices=['x', 'y', 0, 0]` in (Matplotlib) subplots when adding the `wcs` information, and loading the data with axes [0,0,:,:].
However, so far, a similar approach when using APLpy 2.x is not working.

**Comment by bmarcote** [comment]
Ok to add over that, the reason of why APLpy 1.1.1 was not affected  is likely because it was not using Astropy WCS. In that sense this part was not affected by their versions.

From its behavior, I would say that it seems like the WCS part keep all dimensions from the original FITS file, even when in FITSFigure the `dimensions` and `slices` parameters are set. For this reason, it is unable to run some operations.

**Comment by o-smirnov** [comment]
I can confirm all of the above. There seems to be no way to plot 4D images with aplpy 2.x, leaving us radio people somewhat stuck. Here's an ugly but quick hack to drop two axes from the FITS image, if anyone needs it:

```python
from astropy.io import fits

def drop2axes(filename, outname):
    hdu = fits.open(filename)[0]
    for kw in "CTYPE", "CRVAL", "CRPIX", "CDELT", "CUNIT":
        for n in 3, 4:
            hdu.header.remove(f"{kw}{n}")
    fits.writeto(outname, hdu.data[0,0], hdu.header, clobber=True)
```

**Comment by bmarcote** [comment]
There is a more direct solution that do not require creating new FITS files.

```python
def fix_aplpy_fits(aplpy_obj, dropaxis=2):
    """This removes the degenerated dimensions in APLpy 2.X...
    The input must be the object returned by aplpy.FITSFigure().
    `dropaxis` is the index where to start dropping the axis (by default it assumes the 3rd,4th place).
    """
    temp_wcs = aplpy_obj._wcs.dropaxis(2)
    temp_wcs = temp_wcs.dropaxis(2)
    aplpy_obj._wcs = temp_wcs


# Then you can just do the following every time you load a FITS figure:
fig = aplpy.FITSFigure('fitsfilename')
fix_aplpy_fits(fig)
```

This could directly be implemented in APLpy by checking if there are  degenerated axes and drop them in the same way, which would replicate the behavor of APLpy 1.X.

**Comment by o-smirnov** [comment]
Ahh, even better, thanks!

**Comment by kirxkirx** [comment]
@bmarcote thanks for the function that fixes the issue!
