### ISSUE TITLE
ValueError: arange: cannot compute length

### ISSUE THREAD

**Issue by brewstronomy** [aplpy/aplpy#426]
Hi,

Similar to #397, when I try to load an aplpy.FITSFigure instance, I receive the ValueError listed in the title. I have Anaconda3 running on a macOS (v10.12), and I recently updated to Python3.6.8. My aplpy version is 2.0.3.

I have tried it in the following contexts:

- via the IPython console in Spyder (v3.3.4 running IPython v7.2.0)
- via an IPython console on my command line
- via a Python shell

I'd like to emphasize that this is "solved" if I revert to aplpy v1.1.1 but I would like to keep the newer version, if possible.

I assume it has something to do with having a 64-bit system? I noticed that [Anaconda](https://anaconda.org/astropy/aplpy) lists both v1.1.1 and v2.0.3 for Apple products, but specifies v1.1.1 for osx-64. Is this currently an insurmountable obstacle? Thanks for any help!

The full error is as follows:

> INFO: Setting slices=[0] [aplpy.core]
> 
> /Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/formatter_locator.py:129: RuntimeWarning: divide by zero encountered in double_scalars
>   imin = np.ceil(value_min / spacing)
> /Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/formatter_locator.py:130: RuntimeWarning: divide by zero encountered in double_scalars
>   imax = np.floor(value_max / spacing)
> /Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/formatter_locator.py:131: RuntimeWarning: invalid value encountered in double_scalars
>   values = np.arange(imin, imax + 1, dtype=int)
> Traceback (most recent call last):
> 
>   File "<ipython-input-5-18dd72a30ae2>", line 1, in <module>
>     fig = aplpy.FITSFigure('PiscesA_HI.cube.foundation.pbcor.fits')
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 860, in __init__
>     func = make_function_with_signature(func, name=name, **wrapped_args)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/aplpy/decorators.py", line 33, in wrapper
>     args[0]._figure.canvas.draw()
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
>     self.figure.draw(self.renderer)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
>     return draw(artist, renderer, *args, **kwargs)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1649, in draw
>     renderer, self, artists, self.suppressComposite)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
>     a.draw(renderer)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py", line 458, in draw
>     super().draw(renderer, inframe=inframe)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
>     return draw(artist, renderer, *args, **kwargs)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2628, in draw
>     mimage._draw_list_compositing_images(renderer, self, artists)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
>     a.draw(renderer)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py", line 49, in draw
>     self.axes.draw_wcsaxes(renderer)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py", line 415, in draw_wcsaxes
>     coord._draw_grid(renderer)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/coordinate_helpers.py", line 526, in _draw_grid
>     self._update_ticks()
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/coordinate_helpers.py", line 590, in _update_ticks
>     minor_ticks_w_coordinates = self._formatter_locator.minor_locator(self._fl_spacing, self.get_minor_frequency(), *coord_range[self.coord_index])
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/formatter_locator.py", line 113, in minor_locator
>     values = self._locate_values(value_min, value_max, minor_spacing)
> 
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/formatter_locator.py", line 131, in _locate_values
>     values = np.arange(imin, imax + 1, dtype=int)
> 
> ValueError: arange: cannot compute length
> 
> /Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/formatter_locator.py:129: RuntimeWarning: divide by zero encountered in double_scalars
>   imin = np.ceil(value_min / spacing)
> /Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/formatter_locator.py:130: RuntimeWarning: divide by zero encountered in double_scalars
>   imax = np.floor(value_max / spacing)
> /Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/formatter_locator.py:131: RuntimeWarning: invalid value encountered in double_scalars
>   values = np.arange(imin, imax + 1, dtype=int)
> Traceback (most recent call last):
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 519, in _draw_idle
>     self.draw()
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
>     self.figure.draw(self.renderer)
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
>     return draw(artist, renderer, *args, **kwargs)
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1649, in draw
>     renderer, self, artists, self.suppressComposite)
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
>     a.draw(renderer)
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py", line 458, in draw
>     super().draw(renderer, inframe=inframe)
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
>     return draw(artist, renderer, *args, **kwargs)
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2628, in draw
>     mimage._draw_list_compositing_images(renderer, self, artists)
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
>     a.draw(renderer)
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py", line 49, in draw
>     self.axes.draw_wcsaxes(renderer)
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py", line 415, in draw_wcsaxes
>     coord._draw_grid(renderer)
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/coordinate_helpers.py", line 526, in _draw_grid
>     self._update_ticks()
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/coordinate_helpers.py", line 590, in _update_ticks
>     minor_ticks_w_coordinates = self._formatter_locator.minor_locator(self._fl_spacing, self.get_minor_frequency(), *coord_range[self.coord_index])
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/formatter_locator.py", line 113, in minor_locator
>     values = self._locate_values(value_min, value_max, minor_spacing)
>   File "/Users/luca/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/formatter_locator.py", line 131, in _locate_values
>     values = np.arange(imin, imax + 1, dtype=int)
> ValueError: arange: cannot compute length

**Comment by bmarcote** [comment]
Same problem with Aplpy 2.0.3 in a GNU/Linux Debian machine. It produces the same exception for any FITS file that were working properly with Aplpy 1.* versions.
