### ISSUE TITLE
Can not plot contours

### ISSUE THREAD

**Issue by ShanghuoLi** [aplpy/aplpy#429]
version: aplpy 3.1
I attempt to plot contours using the moment-0 generated by CASA.
'fig0.show_contour(mom0, colors='lime', linewidths=1, levels=rms*c_levs)'

I get the error:
ValueError: WCS has more than 2 dimensions, so ``slice`` should be set

Then I setup the slices in show_contours, but I still get the same error.
'fig0.show_contour(mom0,slices=[0] colors='lime', linewidths=1, levels=rms*c_levs)'

The full traceback: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-b0e44c0921b9> in <module>
     91     rms=0.011
     92     c_levs=np.arange(3,40,3)
---> 93     fig0.show_contour(h13cop_mom0, colors='lime', linewidths=1, levels=rms*c_levs)
     94     #     fig0.show_ellipses(x_world, y_world, width/3600, height/3600, position_angle-90,
     95 #                        edgecolor='k', alpha=1, linewidth=1)

~/anaconda3/lib/python3.6/site-packages/astropy/utils/decorators.py in show_contour(self, data, hdu, layer, levels, filled, cmap, colors, returnlevels, convention, dimensions, slices, smooth, kernel, overlap, **kwargs)
    858             name = func.__name__
    859 
--> 860         func = make_function_with_signature(func, name=name, **wrapped_args)
    861         func = functools.update_wrapper(func, wrapped, assigned=assigned,
    862                                         updated=updated)

~/anaconda3/lib/python3.6/site-packages/aplpy/decorators.py in wrapper(*args, **kwargs)
     26 
     27         try:
---> 28             return f(*args, **kwargs)
     29         finally:
     30             mydata.nesting -= 1

~/anaconda3/lib/python3.6/site-packages/aplpy/core.py in show_contour(self, data, hdu, layer, levels, filled, cmap, colors, returnlevels, convention, dimensions, slices, smooth, kernel, overlap, **kwargs)
    965         else:
    966             c = self.ax.contour(image_contour, levels,
--> 967                                 transform=self.ax.get_transform(frame),
    968                                 cmap=cmap,
    969                                 colors=colors, **kwargs)

~/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py in get_transform(self, frame)
    542                 * :class:`~astropy.coordinates.BaseCoordinateFrame` instance.
    543         """
--> 544         return self._get_transform_no_transdata(frame).inverted() + self.transData
    545 
    546     def _get_transform_no_transdata(self, frame):

~/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/core.py in _get_transform_no_transdata(self, frame)
    566                 return (WCSPixel2WorldTransform(self.wcs, slice=self.slices) +
    567                         CoordinateTransform(self.wcs, frame) +
--> 568                         WCSWorld2PixelTransform(frame))
    569 
    570         elif frame == 'pixel':

~/anaconda3/lib/python3.6/site-packages/astropy/visualization/wcsaxes/transforms.py in __init__(self, wcs, slice)
     69         if self.wcs.wcs.naxis > 2:
     70             if slice is None:
---> 71                 raise ValueError("WCS has more than 2 dimensions, so ``slice`` should be set")
     72             elif len(slice) != self.wcs.wcs.naxis:
     73                 raise ValueError("slice should have as many elements as WCS "

ValueError: WCS has more than 2 dimensions, so ``slice`` should be set

**Comment by iwstephens** [comment]
I also had problems with this, though a little bit different error (using Python3). I downgraded to aplpy 1.1.1, and the error went away.

Traceback (most recent call last):
  File "co_moment_maker_rp-1.py", line 35, in <module>
    make_moment_map(source,red_file,blue_file,cont_file,red_contours,blue_contours,cont_contours,robust=-1)
  File "/Users/istephens/Desktop/MASSES/full_release/co_moment_maker_helper.py", line 138, in make_moment_map
    fig.show_contour(red_file, colors='red',levels=red_contours,linewidths=3,zorder=5,smooth=smooth)
  File "/Users/istephens/anaconda2/lib/python3.7/site-packages/astropy/utils/decorators.py", line 860, in show_contour
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "/Users/istephens/anaconda2/lib/python3.7/site-packages/aplpy/decorators.py", line 28, in wrapper
    return f(*args, **kwargs)
  File "/Users/istephens/anaconda2/lib/python3.7/site-packages/aplpy/core.py", line 967, in show_contour
    transform=self.ax.get_transform(frame),
  File "/Users/istephens/anaconda2/lib/python3.7/site-packages/astropy/visualization/wcsaxes/core.py", line 544, in get_transform
    return self._get_transform_no_transdata(frame).inverted() + self.transData
  File "/Users/istephens/anaconda2/lib/python3.7/site-packages/astropy/visualization/wcsaxes/core.py", line 567, in _get_transform_no_transdata
    CoordinateTransform(self.wcs, frame) +
  File "/Users/istephens/anaconda2/lib/python3.7/site-packages/matplotlib/transforms.py", line 1242, in __add__
    return composite_transform_factory(self, other)
  File "/Users/istephens/anaconda2/lib/python3.7/site-packages/matplotlib/transforms.py", line 2494, in composite_transform_factory
    return CompositeGenericTransform(a, b)
  File "/Users/istephens/anaconda2/lib/python3.7/site-packages/matplotlib/transforms.py", line 2310, in __init__
    raise ValueError("The output dimension of 'a' must be equal to "
ValueError: The output dimension of 'a' must be equal to the input dimensions of 'b'

**Comment by jt2553** [comment]
Same here.  Going back to version 1.1.1 fixed it for me as well

**Comment by Jiangxuejian** [comment]
Same here. Have to use spectral_cube to generate a moment 0 map first, so that the NAXIS is changed to 2 instead of 3.

`mom0=cube.moment(order=0)`
`mom0.write('moment_0.fits') `
