### ISSUE TITLE
pip install with python3.8 fails shapely error

### ISSUE THREAD

**Issue by bsipocz** [aplpy/aplpy#439]
this is upstream, but nevertheless shows that there are issued with python3.8 and aplpy

```
$ pip install aplpy
Collecting aplpy
  Using cached https://files.pythonhosted.org/packages/92/5b/cb15d46774105bc536165f2ffa9e114509915f5983c51666512752635b8c/APLpy-2.0.3-py2.py3-none-any.whl
Requirement already satisfied: numpy in /Users/bsipocz/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from aplpy) (1.18.0)
Collecting reproject>=0.4 (from aplpy)
  Using cached https://files.pythonhosted.org/packages/e1/e6/7a6d053302565f535899309638ee9a17ea5a1e60bd11373023b29a9aee45/reproject-0.6-cp38-cp38-macosx_10_9_x86_64.whl
Requirement already satisfied: matplotlib>=2.0 in /Users/bsipocz/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from aplpy) (3.1.2)
Requirement already satisfied: pillow>=4.0 in /Users/bsipocz/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from aplpy) (6.2.1)
Requirement already satisfied: astropy>=3.1 in /Users/bsipocz/.pyenv/versions/3.8.0/lib/python3.8/site-packages (from aplpy) (4.0)
Collecting pyavm>=0.9.4 (from aplpy)
  Using cached https://files.pythonhosted.org/packages/dc/5c/da82e7976856dbea5e3b79815e59c0614406601cc628dc2ded65fd9da4f1/PyAVM-0.9.4-py2.py3-none-any.whl
Collecting shapely>=1.6 (from aplpy)
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/Shapely-1.6.4.post2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/bsipocz/.pyenv/versions/3.8.0/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/pip-install-2p__yiuw/shapely/setup.py'"'"'; __file__='"'"'/private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/pip-install-2p__yiuw/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/pip-install-2p__yiuw/shapely/
    Complete output (11 lines):
    Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
    Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/pip-install-2p__yiuw/shapely/setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "/private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/pip-install-2p__yiuw/shapely/shapely/_buildcfg.py", line 185, in <module>
        lgeos = load_dll('geos_c', fallbacks=alt_paths)
      File "/private/var/folders/dc/hsm7tqpx2d57n7vb3k1l81xw0000gq/T/pip-install-2p__yiuw/shapely/shapely/_buildcfg.py", line 159, in load_dll
        raise OSError(
    OSError: Could not find library geos_c or load any of its variants ['/Library/Frameworks/GEOS.framework/Versions/Current/GEOS', '/opt/local/lib/libgeos_c.dylib']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**Comment by astrofrog** [comment]
Thanks! We currently pin shapely to not be installed when on Python 3.8 due to this, so not much more we can do until they have wheels for 3.8.
